"""
Django settings for etcd3d project.

Generated by 'django-admin startproject' using Django 1.8.15.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import logging

_LOG = logging.getLogger(__name__)

BASE_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), '..')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '6^y2km@_fu@u!om604u&1$qe$v6y-g5pnw+o4oi_rqn1#i)$53'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bootstrap4',
    'corsheaders',
    'rest_framework',
    'djng',
    'etcd3d',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'djng.middleware.AngularUrlMiddleware',
)

MIDDLEWARE = (
   'django.middleware.common.CommonMiddleware',
   'django.contrib.sessions.middleware.SessionMiddleware',
   'django.contrib.messages.middleware.MessageMiddleware',
   'django.middleware.locale.LocaleMiddleware',
   'corsheaders.middleware.CorsMiddleware',
)

APPEND_SLASH = False
CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_ALLOW_ALL = True

ROOT_URLCONF = 'etcd3d.etcd3_dashboard.urls'

#MESSAGE_STORAGE = 'django.contrib.messages.storage.cookie.CookieStorage'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,  'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.i18n',
                'django.template.context_processors.static',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'builtins': [
                'bootstrap4.templatetags.bootstrap4',
            ],
        },
    },
]

WSGI_APPLICATION = 'etcd3d.etcd3_dashboard.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

BOOTSTRAP4 = {
    'base_url': 'https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/',
    'css_url': {
        'href': 'https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css',
        'integrity': 'sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4',
        'crossorigin': 'anonymous',
    },
    'jquery_url': {
        'url': 'https://code.jquery.com/jquery-3.3.1.min.js',
        'integrity': 'sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=',
        'crossorigin': 'anonymous',
    },
    'javascript_url': {
        'url': 'https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js',
        'integrity': 'sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm',
        'crossorigin': 'anonymous',
    },
    'include_jquery': True,
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
    'node_modules',
    os.path.join(BASE_DIR, 'node_modules'),
)


LOGGING = {
    'version': 1,
    'formatters': {
        'debug': {
            'format': ' '.join([
                "%(asctime)s.%(msecs)03d",
                "%(process)d",
                "%(levelname)s",
                "%(name)s",
                "%(funcName)s",
                "%(pathname)s:%(lineno)d",
                "[-]",
                "%(message)s",
            ])
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'debug'
        },
    },
    'loggers': {
        'app': {
            'handlers': ['console'],
            'level': 'DEBUG',
        },
    },
}

"""
etcd3Dashboard settings
"""

# Dashboard fonts
# https://www.911fonts.com/

FONTS = (
    'Comic Sans MS',
    'fantasy',
    'Verdana',
)

ETCD_SERVICE = {
    'version': 3,
    'host': 'etcd',
    'port': 2379,
}

ETCD_DASHBOARD = {
    'settings_path': os.path.join('.dashboard', 'settings',)
}

ETCD_STORE = {
    'shortcut_path': os.path.join(ETCD_DASHBOARD['settings_path'], 'sc'),
}

KVS_TAG_ICONS = [
    {'tag': 'traefik', 'font': 'Font Awesome 5 Brands', 'icon': 'f1d6'}
]


EXTERNAL_SERVICE = {
    'enable_traefik': True,
}

try:
    from etcd3d.local.local_settings import *
except ImportError:
    _LOG.warning("No local_settings file not found.")
